// this file is generated by script, don't modify it !!!
export const oracleFactoryOffChainAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "string",
        "name": "symbol",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "delayAllowance",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "oracle",
        "type": "address"
      }
    ],
    "name": "CreateOracleOffChain",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "string",
        "name": "symbol",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "delayAllowance",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "oracle",
        "type": "address"
      }
    ],
    "name": "CreateVolatilityOracleOffChain",
    "type": "event"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "symbol", "type": "string" },
      { "internalType": "address", "name": "signer", "type": "address" },
      { "internalType": "uint256", "name": "delayAllowance", "type": "uint256" }
    ],
    "name": "createOracle",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "symbol", "type": "string" },
      { "internalType": "address", "name": "signer", "type": "address" },
      { "internalType": "uint256", "name": "delayAllowance", "type": "uint256" }
    ],
    "name": "createVolatilityOracle",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "symbol", "type": "string" }
    ],
    "name": "getOracle",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "string", "name": "symbol", "type": "string" }
    ],
    "name": "getVolatilityOracle",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "view",
    "type": "function"
  }
]

