// this file is generated by script, don't modify it !!!
import { contractFactory } from '../../shared/utils/index.js';
import { perpetualPoolDpmmAdapter, perpetualPoolRouterDpmmAdapter, lTokenAdapter, pTokenAdapter } from './adapter.js';

import { LToken } from './gen/LToken.js';
import { PToken } from './gen/PToken.js';
import { PerpetualPool} from './gen/PerpetualPool';
import { PerpetualPoolRouter} from './gen/PerpetualPoolRouter';

export const lTokenFactory = contractFactory(lTokenAdapter(LToken));
export const pTokenFactory = contractFactory(pTokenAdapter(PToken));

// dpmm
export const perpetualPoolDpmmFactory = contractFactory(perpetualPoolDpmmAdapter(PerpetualPool));
export const perpetualPoolRouterDpmmFactory = contractFactory(perpetualPoolRouterDpmmAdapter(PerpetualPoolRouter));
