// this file is generated by script, don't modify it !!!
export const deriStakingAbi = [{
        "inputs": [{
                "internalType": "address",
                "name": "deriAddress_",
                "type": "address"
            }, {
                "internalType": "uint256",
                "name": "epochStartTimestamp_",
                "type": "uint256"
            }, {
                "internalType": "uint256",
                "name": "epochEndTimestamp_",
                "type": "uint256"
            }
        ],
        "stateMutability": "nonpayable",
        "type": "constructor"
    }, {
        "anonymous": false,
        "inputs": [{
                "indexed": true,
                "internalType": "address",
                "name": "account",
                "type": "address"
            }, {
                "indexed": false,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256"
            }
        ],
        "name": "Deposit",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
                "indexed": true,
                "internalType": "address",
                "name": "account",
                "type": "address"
            }, {
                "indexed": false,
                "internalType": "uint256",
                "name": "accountScore",
                "type": "uint256"
            }, {
                "indexed": false,
                "internalType": "uint256",
                "name": "totalScore",
                "type": "uint256"
            }
        ],
        "name": "UpdateScore",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
                "indexed": true,
                "internalType": "address",
                "name": "account",
                "type": "address"
            }, {
                "indexed": false,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256"
            }
        ],
        "name": "Withdraw",
        "type": "event"
    }, {
        "inputs": [{
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256"
            }
        ],
        "name": "deposit",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "deriAddress",
        "outputs": [{
                "internalType": "address",
                "name": "",
                "type": "address"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "epochEndTimestamp",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "epochStartTimestamp",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
                "internalType": "address",
                "name": "account",
                "type": "address"
            }
        ],
        "name": "getAccountBalance",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
                "internalType": "address",
                "name": "account",
                "type": "address"
            }
        ],
        "name": "getAccountScore",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "getTotalBalance",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "getTotalScore",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "ownerAddress",
        "outputs": [{
                "internalType": "address",
                "name": "",
                "type": "address"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
                "internalType": "uint256",
                "name": "startTimestamp",
                "type": "uint256"
            }, {
                "internalType": "uint256",
                "name": "endTimestamp",
                "type": "uint256"
            }
        ],
        "name": "setEpochTimestamp",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256"
            }
        ],
        "name": "withdraw",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }
]

