// this file is generated by script, don't modify it !!!
export const pTokenAirdropNULSAbi = [{
        "inputs": [{
                "internalType": "address",
                "name": "bTokenAddress",
                "type": "address"
            }, {
                "internalType": "address",
                "name": "pTokenAddress",
                "type": "address"
            }, {
                "internalType": "address",
                "name": "poolAddress",
                "type": "address"
            }
        ],
        "stateMutability": "nonpayable",
        "type": "constructor"
    }, {
        "anonymous": false,
        "inputs": [{
                "indexed": true,
                "internalType": "address",
                "name": "account",
                "type": "address"
            }, {
                "indexed": true,
                "internalType": "uint256",
                "name": "tokenId",
                "type": "uint256"
            }, {
                "indexed": true,
                "internalType": "uint256",
                "name": "index",
                "type": "uint256"
            }
        ],
        "name": "AirdropPToken",
        "type": "event"
    }, {
        "inputs": [],
        "name": "airdropPToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "getBTokenBalance",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
                "internalType": "address",
                "name": "account",
                "type": "address"
            }
        ],
        "name": "isAirdropPToken",
        "outputs": [{
                "internalType": "bool",
                "name": "",
                "type": "bool"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "isStartAirdrop",
        "outputs": [{
                "internalType": "bool",
                "name": "",
                "type": "bool"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "marginUnit",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "maxAirdropLimit",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "ownerAddress",
        "outputs": [{
                "internalType": "address",
                "name": "",
                "type": "address"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
                "internalType": "uint256",
                "name": "marginUnit_",
                "type": "uint256"
            }
        ],
        "name": "setMarginUnit",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
                "internalType": "uint256",
                "name": "maxAirdropLimit_",
                "type": "uint256"
            }
        ],
        "name": "setMaxAirdropLimit",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
                "internalType": "int256",
                "name": "tradeUnit_",
                "type": "int256"
            }
        ],
        "name": "setTradeUnit",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "startAirdrop",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "stopAirdrop",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "totalAirdropCount",
        "outputs": [{
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "tradeUnit",
        "outputs": [{
                "internalType": "int256",
                "name": "",
                "type": "int256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "withdrawBToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }
]

