// this file is generated by script, don't modify it !!!
// import { contractFactory } from "../../../shared/utils/index.js";
import { contractFactoryWithOpts } from "../../utils/misc.js";
import { deriLensAdapter } from "../adapter/deri_lens.js";
import { deriLensArbiAdapter } from "../adapter/deri_lens_arbi.js";
import { DeriLens } from "../gen/DeriLens.js";
import { DeriLensArbi } from "../gen/DeriLensArbi.js";

export const deriLensFactory = contractFactoryWithOpts(deriLensAdapter(DeriLens));

export const deriLensArbiFactory = contractFactoryWithOpts(deriLensArbiAdapter(DeriLensArbi));

export const deriLensFactoryProxy = (chainId, lensAddress) => {
  if (['42161', '421611'].includes(chainId)) {
    return deriLensArbiFactory(chainId, lensAddress)
  } else {
    return deriLensFactory(chainId, lensAddress)
  }
}