// this file is generated by script, don't modify it !!!
import {
  ERC20Adapter,
  dTokenAdapter,
  vBEP20Adapter,
  vBNBAdapter,
  tokenVaultAdapter,
  vaultImplementationAdapter,
  symbolImplementationFuturesAdapter,
  symbolImplementationOptionAdapter,
  symbolManagerImplementationAdapter,
  oracleManagerAdapter,
  oracleChainlinkAdapter,
  oracleWooAdapter,
  oracleOffChainAdapter,
  venusControllerAdapter,
  symbolImplementationPowerAdapter,
  pTokenAirdropV3Adapter,
  rewardVaultAdapter,
  VoteAdapter,
} from "../adapter/rest.js";

import { ERC20 } from "../gen/ERC20.js";
import { DToken } from "../gen/DToken.js";
import { VBEP20 } from "../gen/VBEP20.js";
import { VBNB } from "../gen/VBNB.js";
import { TokenVault } from "../gen/TokenVault.js";
import { VaultImplementation } from "../gen/VaultImplementation.js";
import { SymbolManagerImplementation } from "../gen/SymbolManagerImplementation.js";
import { SymbolImplementationFutures } from "../gen/SymbolImplementationFutures.js";
import { SymbolImplementationOption } from "../gen/SymbolImplementationOption.js";
import { OracleManager } from '../gen/OracleManager.js';
import { OracleChainlink } from '../gen/OracleChainlink.js';
import { OracleWoo } from '../gen/OracleWoo.js';
import { OracleOffChain } from '../gen/OracleOffChain.js';
import { VenusController } from '../gen/VenusController.js';
import { SymbolImplementationPower } from "../gen/SymbolImplementationPower.js";
import { MintableERC20 } from "../gen/MintableERC20.js";
import { RewardVault } from "../gen/RewardVault.js";
import { Vote } from "../gen/Vote";
import { contractFactoryWithOpts } from "../../utils/misc.js";
import { contractFactory } from "../../../shared/utils/web3next.js";

export const ERC20Factory = contractFactory(ERC20Adapter(ERC20));
export const mintableERC20Factory = contractFactory(MintableERC20);
export const dTokenFactory = contractFactory(dTokenAdapter(DToken));
export const vBEP20Factory = contractFactory(vBEP20Adapter(VBEP20));
export const vBNBFactory = contractFactory(vBNBAdapter(VBNB));
export const tokenVaultFactory = contractFactory(tokenVaultAdapter(TokenVault));
export const vaultImplementationFactory = contractFactory(
  vaultImplementationAdapter(VaultImplementation)
);
export const symbolManagerImplementationFactory = contractFactory(
  symbolManagerImplementationAdapter(SymbolManagerImplementation)
);
export const symbolImplementationFuturesFactory = contractFactory(
  symbolImplementationFuturesAdapter(SymbolImplementationFutures)
);
export const symbolImplementationOptionFactory = contractFactory(
  symbolImplementationOptionAdapter(SymbolImplementationOption)
);
export const symbolImplementationPowerFactory = contractFactory(
  symbolImplementationPowerAdapter(SymbolImplementationPower)
);
export const oracleManagerFactory = contractFactory(oracleManagerAdapter(OracleManager));
export const oracleChainlinkFactory = contractFactory(oracleChainlinkAdapter(OracleChainlink));
export const oracleWooFactory = contractFactory(oracleWooAdapter(OracleWoo));
export const oracleOffChainFactory = contractFactory(oracleOffChainAdapter(OracleOffChain));
export const venusControllerFactory = contractFactory(venusControllerAdapter(VenusController));

export const rewardVaultFactory = contractFactory(rewardVaultAdapter(RewardVault));
export const voteFactory = contractFactoryWithOpts(VoteAdapter(Vote));