// this file is generated by script, don't modify it !!!
import { processMethod } from "../utils/web3next.js";
import { bg } from "../../shared/utils/index.js";
import { MAX_UINT256} from '../config'

const isUnlocked = (klass) => {
  klass.prototype["isUnlocked"] = async function (accountAddress, poolAddress) {
    const allowance = await this.allowance(accountAddress, poolAddress)
    //console.log(accountAddress, poolAddress)
    const res = bg(allowance).gt(0)
    return res
  };
  return klass
};

const unlock = (klass) => {
  klass.prototype['unlock'] = async function (accountAddress, poolAddress, opts) {
    return await this._transact(
      'approve',
      [poolAddress, MAX_UINT256],
      accountAddress,
      opts,
    );
  };
  return klass;
};

export const ERC20Adapter = (klass) => {
    klass = processMethod(klass, 'totalSupply');
    //klass = processMethod(klass, 'balanceOf'); // use ERC20.decimals

    klass = isUnlocked(klass);
    klass = unlock(klass);
    return klass
}