// this file is generated by script, don't modify it !!!
import { contractFactory } from '../utils/web3next.js';
import {
  ERC20Adapter,
} from './adapter.js';

import { ERC20 } from './gen/ERC20.js';

// ERC20
export const ERC20Factory = contractFactory(ERC20Adapter(ERC20));
export const bTokenFactory = ERC20Factory


