// this file is generated by script, don't modify it !!!
import { ContractBase } from './contract_base'
import { deleteIndexedKey } from '../utils'
import { TERC20Abi } from './abis'

export class TERC20 extends ContractBase {
  // init
  constructor(chainId, contractAddress) {
    super(chainId, contractAddress, TERC20Abi)
  }

  // query
  async allowance(owner, spender) {
    const res = await this._call('allowance', [owner, spender])
    return deleteIndexedKey(res)
  }
  async balanceOf(account) {
    const res = await this._call('balanceOf', [account])
    return deleteIndexedKey(res)
  }
  //  async decimals() {
  //    const res = await this._call('decimals', [])
  //    return deleteIndexedKey(res)
  //  }
  //  async name() {
  //    const res = await this._call('name', [])
  //    return deleteIndexedKey(res)
  //  }
  async symbol() {
    const res = await this._call('symbol', [])
    return deleteIndexedKey(res)
  }
  async totalSupply() {
    const res = await this._call('totalSupply', [])
    return deleteIndexedKey(res)
  }

  // tx
  async approve(accountAddress, spender, amount) {
    return await this._transact('approve', [spender, amount], accountAddress)
  }
  // only for testnet
  async mint(accountAddress) {
    return await this._transact('mint', [], accountAddress)
  }
  //  async transfer(accountAddress, to, amount) {
  //    return await this._transact('transfer', [to, amount], accountAddress)
  //  }
  //  async transferFrom(accountAddress, from, to, amount) {
  //    return await this._transact('transferFrom', [from, to, amount], accountAddress)
  //  }

}