// this file is generated by script, don't modify it !!!
export const deriViewAbi = [
    {
        "inputs": [
            {
                "internalType": "address",
                "name": "poolAddress_",
                "type": "address"
            }
        ],
        "stateMutability": "nonpayable",
        "type": "constructor"
    },
    {
        "inputs": [
            {
                "internalType": "address",
                "name": "account",
                "type": "address"
            }
        ],
        "name": "getData",
        "outputs": [
            {
                "components": [
                    {
                        "components": [
                            {
                                "internalType": "address",
                                "name": "vaultTemplate",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "vaultImplementation",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "tokenB0",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "tokenWETH",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "vTokenB0",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "vTokenETH",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "lToken",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "pToken",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "oracleManager",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "swapper",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "symbolManager",
                                "type": "address"
                            },
                            {
                                "internalType": "uint256",
                                "name": "keepRatioB0",
                                "type": "uint256"
                            },
                            {
                                "internalType": "int256",
                                "name": "minRatioB0",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "poolInitialMarginMultiplier",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "protocolFeeCollectRatio",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "minLiquidationReward",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "maxLiquidationReward",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "liquidationRewardCutRatio",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "liquidity",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "lpsPnl",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "cumulativePnlPerLiquidity",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "protocolFeeAccrued",
                                "type": "int256"
                            }
                        ],
                        "internalType": "struct DeriView.Pool",
                        "name": "pool",
                        "type": "tuple"
                    },
                    {
                        "components": [
                            {
                                "internalType": "int256",
                                "name": "initialMarginRequired",
                                "type": "int256"
                            }
                        ],
                        "internalType": "struct DeriView.SymbolManager",
                        "name": "symbolManager",
                        "type": "tuple"
                    },
                    {
                        "components": [
                            {
                                "internalType": "string",
                                "name": "category",
                                "type": "string"
                            },
                            {
                                "internalType": "address",
                                "name": "symbolAddress",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "implementation",
                                "type": "address"
                            },
                            {
                                "internalType": "string",
                                "name": "symbol",
                                "type": "string"
                            },
                            {
                                "internalType": "int256",
                                "name": "netVolume",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "netCost",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "indexPrice",
                                "type": "int256"
                            },
                            {
                                "internalType": "uint256",
                                "name": "fundingTimestamp",
                                "type": "uint256"
                            },
                            {
                                "internalType": "int256",
                                "name": "cumulativeFundingPerVolume",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "tradersPnl",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "initialMarginRequired",
                                "type": "int256"
                            },
                            {
                                "internalType": "uint256",
                                "name": "nPositionHolders",
                                "type": "uint256"
                            },
                            {
                                "internalType": "address",
                                "name": "manager",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "oracleManager",
                                "type": "address"
                            },
                            {
                                "internalType": "bytes32",
                                "name": "symbolId",
                                "type": "bytes32"
                            },
                            {
                                "internalType": "int256",
                                "name": "alpha",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "fundingPeriod",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "minTradeVolume",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "initialMarginRatio",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "maintenanceMarginRatio",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "pricePercentThreshold",
                                "type": "int256"
                            },
                            {
                                "internalType": "uint256",
                                "name": "timeThreshold",
                                "type": "uint256"
                            },
                            {
                                "internalType": "bool",
                                "name": "isCloseOnly",
                                "type": "bool"
                            },
                            {
                                "internalType": "int256",
                                "name": "feeRatio",
                                "type": "int256"
                            },
                            {
                                "internalType": "bytes32",
                                "name": "priceId",
                                "type": "bytes32"
                            },
                            {
                                "internalType": "bytes32",
                                "name": "volatilityId",
                                "type": "bytes32"
                            },
                            {
                                "internalType": "int256",
                                "name": "feeRatioITM",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "feeRatioOTM",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "strikePrice",
                                "type": "int256"
                            },
                            {
                                "internalType": "bool",
                                "name": "isCall",
                                "type": "bool"
                            },
                            {
                                "internalType": "uint256",
                                "name": "curIndexPrice",
                                "type": "uint256"
                            },
                            {
                                "internalType": "uint256",
                                "name": "curVolatility",
                                "type": "uint256"
                            }
                        ],
                        "internalType": "struct DeriView.Symbol[]",
                        "name": "symbols",
                        "type": "tuple[]"
                    },
                    {
                        "components": [
                            {
                                "internalType": "address",
                                "name": "account",
                                "type": "address"
                            },
                            {
                                "internalType": "uint256",
                                "name": "lTokenId",
                                "type": "uint256"
                            },
                            {
                                "internalType": "address",
                                "name": "vault",
                                "type": "address"
                            },
                            {
                                "internalType": "int256",
                                "name": "amountB0",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "liquidity",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "cumulativePnlPerLiquidity",
                                "type": "int256"
                            },
                            {
                                "internalType": "uint256",
                                "name": "borrowLimit",
                                "type": "uint256"
                            },
                            {
                                "components": [
                                    {
                                        "internalType": "address",
                                        "name": "vToken",
                                        "type": "address"
                                    },
                                    {
                                        "internalType": "address",
                                        "name": "underlying",
                                        "type": "address"
                                    },
                                    {
                                        "internalType": "string",
                                        "name": "vTokenSymbol",
                                        "type": "string"
                                    },
                                    {
                                        "internalType": "string",
                                        "name": "underlyingSymbol",
                                        "type": "string"
                                    },
                                    {
                                        "internalType": "uint256",
                                        "name": "vTokenBalance",
                                        "type": "uint256"
                                    },
                                    {
                                        "internalType": "uint256",
                                        "name": "exchangeRate",
                                        "type": "uint256"
                                    }
                                ],
                                "internalType": "struct DeriView.MarketInfo[]",
                                "name": "markets",
                                "type": "tuple[]"
                            }
                        ],
                        "internalType": "struct DeriView.LpInfo",
                        "name": "lpInfo",
                        "type": "tuple"
                    },
                    {
                        "components": [
                            {
                                "internalType": "address",
                                "name": "account",
                                "type": "address"
                            },
                            {
                                "internalType": "uint256",
                                "name": "pTokenId",
                                "type": "uint256"
                            },
                            {
                                "internalType": "address",
                                "name": "vault",
                                "type": "address"
                            },
                            {
                                "internalType": "int256",
                                "name": "amountB0",
                                "type": "int256"
                            },
                            {
                                "internalType": "uint256",
                                "name": "borrowLimit",
                                "type": "uint256"
                            },
                            {
                                "components": [
                                    {
                                        "internalType": "address",
                                        "name": "vToken",
                                        "type": "address"
                                    },
                                    {
                                        "internalType": "address",
                                        "name": "underlying",
                                        "type": "address"
                                    },
                                    {
                                        "internalType": "string",
                                        "name": "vTokenSymbol",
                                        "type": "string"
                                    },
                                    {
                                        "internalType": "string",
                                        "name": "underlyingSymbol",
                                        "type": "string"
                                    },
                                    {
                                        "internalType": "uint256",
                                        "name": "vTokenBalance",
                                        "type": "uint256"
                                    },
                                    {
                                        "internalType": "uint256",
                                        "name": "exchangeRate",
                                        "type": "uint256"
                                    }
                                ],
                                "internalType": "struct DeriView.MarketInfo[]",
                                "name": "markets",
                                "type": "tuple[]"
                            },
                            {
                                "components": [
                                    {
                                        "internalType": "address",
                                        "name": "symbolAddress",
                                        "type": "address"
                                    },
                                    {
                                        "internalType": "string",
                                        "name": "symbol",
                                        "type": "string"
                                    },
                                    {
                                        "internalType": "int256",
                                        "name": "volume",
                                        "type": "int256"
                                    },
                                    {
                                        "internalType": "int256",
                                        "name": "cost",
                                        "type": "int256"
                                    },
                                    {
                                        "internalType": "int256",
                                        "name": "cumulativeFundingPerVolume",
                                        "type": "int256"
                                    }
                                ],
                                "internalType": "struct DeriView.PositionInfo[]",
                                "name": "positions",
                                "type": "tuple[]"
                            }
                        ],
                        "internalType": "struct DeriView.TdInfo",
                        "name": "tdInfo",
                        "type": "tuple"
                    }
                ],
                "internalType": "struct DeriView.Data",
                "name": "data",
                "type": "tuple"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {
                "internalType": "address",
                "name": "account",
                "type": "address"
            }
        ],
        "name": "getLpInfo",
        "outputs": [
            {
                "components": [
                    {
                        "internalType": "address",
                        "name": "account",
                        "type": "address"
                    },
                    {
                        "internalType": "uint256",
                        "name": "lTokenId",
                        "type": "uint256"
                    },
                    {
                        "internalType": "address",
                        "name": "vault",
                        "type": "address"
                    },
                    {
                        "internalType": "int256",
                        "name": "amountB0",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "liquidity",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "cumulativePnlPerLiquidity",
                        "type": "int256"
                    },
                    {
                        "internalType": "uint256",
                        "name": "borrowLimit",
                        "type": "uint256"
                    },
                    {
                        "components": [
                            {
                                "internalType": "address",
                                "name": "vToken",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "underlying",
                                "type": "address"
                            },
                            {
                                "internalType": "string",
                                "name": "vTokenSymbol",
                                "type": "string"
                            },
                            {
                                "internalType": "string",
                                "name": "underlyingSymbol",
                                "type": "string"
                            },
                            {
                                "internalType": "uint256",
                                "name": "vTokenBalance",
                                "type": "uint256"
                            },
                            {
                                "internalType": "uint256",
                                "name": "exchangeRate",
                                "type": "uint256"
                            }
                        ],
                        "internalType": "struct DeriView.MarketInfo[]",
                        "name": "markets",
                        "type": "tuple[]"
                    }
                ],
                "internalType": "struct DeriView.LpInfo",
                "name": "lpInfo",
                "type": "tuple"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "getPoolData",
        "outputs": [
            {
                "components": [
                    {
                        "internalType": "address",
                        "name": "vaultTemplate",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "vaultImplementation",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "tokenB0",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "tokenWETH",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "vTokenB0",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "vTokenETH",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "lToken",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "pToken",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "oracleManager",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "swapper",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "symbolManager",
                        "type": "address"
                    },
                    {
                        "internalType": "uint256",
                        "name": "keepRatioB0",
                        "type": "uint256"
                    },
                    {
                        "internalType": "int256",
                        "name": "minRatioB0",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "poolInitialMarginMultiplier",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "protocolFeeCollectRatio",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "minLiquidationReward",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "maxLiquidationReward",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "liquidationRewardCutRatio",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "liquidity",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "lpsPnl",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "cumulativePnlPerLiquidity",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "protocolFeeAccrued",
                        "type": "int256"
                    }
                ],
                "internalType": "struct DeriView.Pool",
                "name": "pool",
                "type": "tuple"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {
                "internalType": "address",
                "name": "symbolAddress",
                "type": "address"
            }
        ],
        "name": "getSymbol",
        "outputs": [
            {
                "components": [
                    {
                        "internalType": "string",
                        "name": "category",
                        "type": "string"
                    },
                    {
                        "internalType": "address",
                        "name": "symbolAddress",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "implementation",
                        "type": "address"
                    },
                    {
                        "internalType": "string",
                        "name": "symbol",
                        "type": "string"
                    },
                    {
                        "internalType": "int256",
                        "name": "netVolume",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "netCost",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "indexPrice",
                        "type": "int256"
                    },
                    {
                        "internalType": "uint256",
                        "name": "fundingTimestamp",
                        "type": "uint256"
                    },
                    {
                        "internalType": "int256",
                        "name": "cumulativeFundingPerVolume",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "tradersPnl",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "initialMarginRequired",
                        "type": "int256"
                    },
                    {
                        "internalType": "uint256",
                        "name": "nPositionHolders",
                        "type": "uint256"
                    },
                    {
                        "internalType": "address",
                        "name": "manager",
                        "type": "address"
                    },
                    {
                        "internalType": "address",
                        "name": "oracleManager",
                        "type": "address"
                    },
                    {
                        "internalType": "bytes32",
                        "name": "symbolId",
                        "type": "bytes32"
                    },
                    {
                        "internalType": "int256",
                        "name": "alpha",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "fundingPeriod",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "minTradeVolume",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "initialMarginRatio",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "maintenanceMarginRatio",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "pricePercentThreshold",
                        "type": "int256"
                    },
                    {
                        "internalType": "uint256",
                        "name": "timeThreshold",
                        "type": "uint256"
                    },
                    {
                        "internalType": "bool",
                        "name": "isCloseOnly",
                        "type": "bool"
                    },
                    {
                        "internalType": "int256",
                        "name": "feeRatio",
                        "type": "int256"
                    },
                    {
                        "internalType": "bytes32",
                        "name": "priceId",
                        "type": "bytes32"
                    },
                    {
                        "internalType": "bytes32",
                        "name": "volatilityId",
                        "type": "bytes32"
                    },
                    {
                        "internalType": "int256",
                        "name": "feeRatioITM",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "feeRatioOTM",
                        "type": "int256"
                    },
                    {
                        "internalType": "int256",
                        "name": "strikePrice",
                        "type": "int256"
                    },
                    {
                        "internalType": "bool",
                        "name": "isCall",
                        "type": "bool"
                    },
                    {
                        "internalType": "uint256",
                        "name": "curIndexPrice",
                        "type": "uint256"
                    },
                    {
                        "internalType": "uint256",
                        "name": "curVolatility",
                        "type": "uint256"
                    }
                ],
                "internalType": "struct DeriView.Symbol",
                "name": "symbol",
                "type": "tuple"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {
                "internalType": "address",
                "name": "symbolManagerAddress",
                "type": "address"
            }
        ],
        "name": "getSymbolManagerData",
        "outputs": [
            {
                "components": [
                    {
                        "internalType": "int256",
                        "name": "initialMarginRequired",
                        "type": "int256"
                    }
                ],
                "internalType": "struct DeriView.SymbolManager",
                "name": "symbolManager",
                "type": "tuple"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {
                "internalType": "address",
                "name": "account",
                "type": "address"
            }
        ],
        "name": "getTdInfo",
        "outputs": [
            {
                "components": [
                    {
                        "internalType": "address",
                        "name": "account",
                        "type": "address"
                    },
                    {
                        "internalType": "uint256",
                        "name": "pTokenId",
                        "type": "uint256"
                    },
                    {
                        "internalType": "address",
                        "name": "vault",
                        "type": "address"
                    },
                    {
                        "internalType": "int256",
                        "name": "amountB0",
                        "type": "int256"
                    },
                    {
                        "internalType": "uint256",
                        "name": "borrowLimit",
                        "type": "uint256"
                    },
                    {
                        "components": [
                            {
                                "internalType": "address",
                                "name": "vToken",
                                "type": "address"
                            },
                            {
                                "internalType": "address",
                                "name": "underlying",
                                "type": "address"
                            },
                            {
                                "internalType": "string",
                                "name": "vTokenSymbol",
                                "type": "string"
                            },
                            {
                                "internalType": "string",
                                "name": "underlyingSymbol",
                                "type": "string"
                            },
                            {
                                "internalType": "uint256",
                                "name": "vTokenBalance",
                                "type": "uint256"
                            },
                            {
                                "internalType": "uint256",
                                "name": "exchangeRate",
                                "type": "uint256"
                            }
                        ],
                        "internalType": "struct DeriView.MarketInfo[]",
                        "name": "markets",
                        "type": "tuple[]"
                    },
                    {
                        "components": [
                            {
                                "internalType": "address",
                                "name": "symbolAddress",
                                "type": "address"
                            },
                            {
                                "internalType": "string",
                                "name": "symbol",
                                "type": "string"
                            },
                            {
                                "internalType": "int256",
                                "name": "volume",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "cost",
                                "type": "int256"
                            },
                            {
                                "internalType": "int256",
                                "name": "cumulativeFundingPerVolume",
                                "type": "int256"
                            }
                        ],
                        "internalType": "struct DeriView.PositionInfo[]",
                        "name": "positions",
                        "type": "tuple[]"
                    }
                ],
                "internalType": "struct DeriView.TdInfo",
                "name": "tdInfo",
                "type": "tuple"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "poolAddress",
        "outputs": [
            {
                "internalType": "address",
                "name": "",
                "type": "address"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }
]

